language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rantdocker/docker-react -f Dockerfile.dev .

script:
  - docker run rantdocker/docker-react npm run test -- --coverage

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
